# docker-compose.yml
version: "3"
services:
  app:
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - ./src:/home/app/src
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      POSTGRES_HOST: postgres:postgres@postgres:5432
      PORT: 3000
